# Generated by Django 2.2.3 on 2019-08-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongne1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongne1',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
