# Generated by Django 2.2 on 2019-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongne1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dongne1',
            name='category2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
